# -*- coding: utf-8 -*-
{
    'name': 'Dean Group International – Manufacturing ERP',
    'version': '17.0.2.0.0',
    'category': 'Manufacturing',
    'summary': 'Complete ERP for Dean Group – Investment Casting, Die Casting, MIM, Forging + Odoo Website',
    'author': 'Zenvora',
    'website': 'https://www.zenvora.com',
    'license': 'LGPL-3',
    'depends': [
        'base', 'mail', 'web', 'portal',
        'website', 'website_blog', 'website_form', 'website_hr_recruitment',
        'mrp', 'mrp_workcenter', 'stock', 'purchase', 'sale_management',
        'crm', 'account', 'hr', 'hr_payroll', 'hr_attendance',
        'hr_holidays', 'hr_recruitment', 'maintenance', 'quality_mrp', 'l10n_uk',
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/company_data.xml',
        'data/casting_processes.xml',
        'data/product_data.xml',
        'data/workcenter_data.xml',
        'data/stock_locations.xml',
        'data/customers_vendors.xml',
        'data/quality_data.xml',
        'data/maintenance_data.xml',
        'data/job_positions.xml',
        'data/crm_data.xml',
        'data/employees_data.xml',
        'data/payroll_rules.xml',
        'data/mail_templates.xml',
        'data/ir_cron.xml',
        'data/website_data.xml',
        'views/casting_views.xml',
        'views/mrp_views.xml',
        'views/quality_views.xml',
        'views/hr_foundry_views.xml',
        'views/china_supply_views.xml',
        'views/menu.xml',
        'views/website_homepage.xml',
        'views/website_services.xml',
        'views/website_markets.xml',
        'views/website_careers.xml',
        'views/website_contact.xml',
        'views/website_templates.xml',
        'wizard/wizard_views.xml',
        'reports/quality_cert_report.xml',
        'reports/casting_delivery_note.xml',
        'reports/payroll_report.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'dean_group_mfg/static/src/css/website.css',
            'dean_group_mfg/static/src/js/website.js',
        ],
        'web.assets_backend': [
            'dean_group_mfg/static/src/css/backend.css',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    'sequence': 1,
}
